BEGIN;

-- ============================================================
-- PERMISOS SOBRE EL ESQUEMA
-- ============================================================

GRANT USAGE ON SCHEMA public TO portalpericialapp;

-- ============================================================
-- TABLA: PERSONAS
-- ============================================================

CREATE TABLE public.personas
(
    personaid             BIGINT GENERATED BY DEFAULT AS IDENTITY,
    nombre                VARCHAR(100) NOT NULL,
    apellido              VARCHAR(100) NOT NULL,
    email                 VARCHAR(255) NOT NULL,
    telefono              VARCHAR(30),
    whatsapp              VARCHAR(30),
    emailvalidado         BOOLEAN NOT NULL DEFAULT FALSE,
    fechaultimoacceso     TIMESTAMPTZ,
    origen                VARCHAR(30) NOT NULL DEFAULT 'WEB',
    activo                BOOLEAN NOT NULL DEFAULT TRUE,
    fechacreacion         TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fechaactualizacion    TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pkpersonas
        PRIMARY KEY (personaid),

    CONSTRAINT ckpersonasnombre
        CHECK (btrim(nombre) <> ''),

    CONSTRAINT ckpersonasapellido
        CHECK (btrim(apellido) <> ''),

    CONSTRAINT ckpersonasemail
        CHECK (btrim(email) <> ''),

    CONSTRAINT ckpersonasorigen
        CHECK (btrim(origen) <> '')
);

COMMENT ON TABLE public.personas IS
    'Personas registradas en Portal Pericial.';

COMMENT ON COLUMN public.personas.email IS
    'Clave de negocio de la persona. La unicidad se controla sin distinguir mayúsculas y minúsculas.';

COMMENT ON COLUMN public.personas.origen IS
    'Origen inicial del registro, por ejemplo WEB, CHARLA, NEWSLETTER, CONSULTA o IMPORTACION.';

-- El email es la clave de negocio y no distingue mayúsculas,
-- minúsculas ni espacios externos.
CREATE UNIQUE INDEX uxpersonasemail
    ON public.personas (lower(btrim(email)));

CREATE INDEX ixpersonasapellidonombre
    ON public.personas (apellido, nombre);

CREATE INDEX ixpersonasactivas
    ON public.personas (personaid)
    WHERE activo = TRUE;

-- ============================================================
-- TABLA: EVENTOS
-- ============================================================

CREATE TABLE public.eventos
(
    eventoid              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    titulo                VARCHAR(200) NOT NULL,
    slug                  VARCHAR(120) NOT NULL,
    descripcion           TEXT,
    fechainicio           TIMESTAMPTZ NOT NULL,
    fechafin              TIMESTAMPTZ NOT NULL,
    capacidad             INTEGER,
    visibleweb            BOOLEAN NOT NULL DEFAULT TRUE,
    activo                BOOLEAN NOT NULL DEFAULT TRUE,
    fechacreacion         TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fechaactualizacion    TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pkeventos
        PRIMARY KEY (eventoid),

    CONSTRAINT uqeventosslug
        UNIQUE (slug),

    CONSTRAINT ckeventostitulo
        CHECK (btrim(titulo) <> ''),

    CONSTRAINT ckeventosslug
        CHECK (
            slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$'
        ),

    CONSTRAINT ckeventosfechas
        CHECK (fechafin > fechainicio),

    CONSTRAINT ckeventoscapacidad
        CHECK (
            capacidad IS NULL
            OR capacidad > 0
        )
);

COMMENT ON TABLE public.eventos IS
    'Eventos, charlas y actividades organizadas por Portal Pericial.';

COMMENT ON COLUMN public.eventos.slug IS
    'Identificador legible utilizado en URLs públicas.';

COMMENT ON COLUMN public.eventos.capacidad IS
    'Cantidad máxima de inscriptos. NULL indica que no existe límite definido.';

CREATE INDEX ixeventosfechainicio
    ON public.eventos (fechainicio);

CREATE INDEX ixeventospublicosproximos
    ON public.eventos (fechainicio)
    WHERE activo = TRUE
      AND visibleweb = TRUE;

-- ============================================================
-- TABLA: INSCRIPCIONESEVENTOS
-- ============================================================

CREATE TABLE public.inscripcioneseventos
(
    inscripcioneventoid   BIGINT GENERATED BY DEFAULT AS IDENTITY,
    personaid             BIGINT NOT NULL,
    eventoid              BIGINT NOT NULL,
    estado                VARCHAR(20) NOT NULL DEFAULT 'INSCRIPTO',
    fechainscripcion      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fechaactualizacion    TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    observaciones         TEXT,

    CONSTRAINT pkinscripcioneseventos
        PRIMARY KEY (inscripcioneventoid),

    CONSTRAINT fkinscripcioneseventospersona
        FOREIGN KEY (personaid)
        REFERENCES public.personas (personaid)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT,

    CONSTRAINT fkinscripcioneseventosevento
        FOREIGN KEY (eventoid)
        REFERENCES public.eventos (eventoid)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT,

    CONSTRAINT uqinscripcioneseventospersonaevento
        UNIQUE (personaid, eventoid),

    CONSTRAINT ckinscripcioneseventosestado
        CHECK (
            estado IN (
                'INSCRIPTO',
                'CONFIRMADO',
                'ASISTIO',
                'AUSENTE',
                'CANCELADO'
            )
        )
);

COMMENT ON TABLE public.inscripcioneseventos IS
    'Inscripciones de personas a eventos. Una persona puede inscribirse a varios eventos, pero solo una vez en cada evento.';

COMMENT ON COLUMN public.inscripcioneseventos.estado IS
    'Estado de la inscripción: INSCRIPTO, CONFIRMADO, ASISTIO, AUSENTE o CANCELADO.';

-- No hace falta un índice independiente por personaid:
-- la restricción UNIQUE (personaid, eventoid) ya genera uno
-- cuyo primer campo es personaid.

CREATE INDEX ixinscripcioneseventoseventoestado
    ON public.inscripcioneseventos (eventoid, estado);

CREATE INDEX ixinscripcioneseventosfechainscripcion
    ON public.inscripcioneseventos (fechainscripcion DESC);

-- ============================================================
-- ACTUALIZACIÓN AUTOMÁTICA DE FECHAACTUALIZACION
-- ============================================================

CREATE OR REPLACE FUNCTION public.actualizarfechaactualizacion()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.fechaactualizacion := CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$;

CREATE TRIGGER trgpersonasfechaactualizacion
BEFORE UPDATE ON public.personas
FOR EACH ROW
EXECUTE FUNCTION public.actualizarfechaactualizacion();

CREATE TRIGGER trgeventosfechaactualizacion
BEFORE UPDATE ON public.eventos
FOR EACH ROW
EXECUTE FUNCTION public.actualizarfechaactualizacion();

CREATE TRIGGER trginscripcioneseventosfechaactualizacion
BEFORE UPDATE ON public.inscripcioneseventos
FOR EACH ROW
EXECUTE FUNCTION public.actualizarfechaactualizacion();

-- ============================================================
-- PERMISOS DEL BACKEND
-- ============================================================

GRANT SELECT, INSERT, UPDATE
ON TABLE
    public.personas,
    public.eventos,
    public.inscripcioneseventos
TO portalpericialapp;

GRANT USAGE, SELECT
ON SEQUENCE
    public.personas_personaid_seq,
    public.eventos_eventoid_seq,
    public.inscripcioneseventos_inscripcioneventoid_seq
TO portalpericialapp;

COMMIT;